// <auto-generated />
using System;
using ArchiLog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArchiLog.Migrations
{
    [DbContext(typeof(ArchiLogDbContext))]
    [Migration("20221028134325_Seeders")]
    partial class Seeders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ArchiLog.Models.Brand", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Slogan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = true,
                            CreatedAt = new DateTime(2022, 10, 28, 13, 43, 25, 265, DateTimeKind.Utc).AddTicks(5366),
                            Name = "Peugeot",
                            Slogan = "Nos voitures pas chères"
                        },
                        new
                        {
                            ID = 2,
                            Active = true,
                            CreatedAt = new DateTime(2022, 10, 28, 13, 43, 25, 265, DateTimeKind.Utc).AddTicks(5369),
                            Name = "Citroën",
                            Slogan = "Nos voitures très chères"
                        });
                });

            modelBuilder.Entity("ArchiLog.Models.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("BrandID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Active = true,
                            BrandID = 1,
                            CreatedAt = new DateTime(2022, 10, 28, 13, 43, 25, 265, DateTimeKind.Utc).AddTicks(5513),
                            Name = "Pas cher V1",
                            Price = 0
                        },
                        new
                        {
                            ID = 2,
                            Active = true,
                            BrandID = 1,
                            CreatedAt = new DateTime(2022, 10, 28, 13, 43, 25, 265, DateTimeKind.Utc).AddTicks(5515),
                            Name = "Pas cher V2",
                            Price = 0
                        });
                });

            modelBuilder.Entity("ArchiLog.Models.Car", b =>
                {
                    b.HasOne("ArchiLog.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });
#pragma warning restore 612, 618
        }
    }
}
